# Generated by Django 4.1.5 on 2023-02-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_product_product_name_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
