# Generated by Django 3.2.18 on 2023-02-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Categories'},
        ),
    ]
