# Generated by Django 3.2.18 on 2023-02-21 15:18

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=django_quill.fields.QuillField(blank=True, default='description'),
        ),
    ]
