# Generated by Django 3.2.18 on 2023-02-21 15:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default='description'),
        ),
    ]
