# Generated by Django 3.2.18 on 2023-02-22 15:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230222_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='Full Blog Post'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='Brief Description', max_length=160),
        ),
    ]
