# Generated by Django 3.2.18 on 2023-03-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230221_1840'),
        ('blog', '0005_auto_20230222_1558'),
    ]

    operations = [
    ]
