# Generated by Django 3.2.18 on 2023-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_city_town',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_county',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
