# Generated by Django 4.1.5 on 2023-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_address_city_town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_city_town',
            field=models.CharField(blank=True, default='Town not choosen', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_county',
            field=models.CharField(blank=True, default='County not choosen', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='Empty', max_length=100),
        ),
    ]
