# Generated by Django 3.2.18 on 2023-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230321_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_city_town',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_county',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
