# Generated by Django 4.1.5 on 2023-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_address_city_town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_city_town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
