# Generated by Django 3.2.18 on 2023-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_doc',
            field=models.FileField(blank=True, upload_to='invoices'),
        ),
    ]
