# Generated by Django 3.2.18 on 2023-02-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
